---
- name: Prepare Windows build environment without win_chocolatey
  hosts: default-windows-11-virtio-copper-mongoose-72
  gather_facts: no

  tasks:
    - name: Install Chocolatey (Windows 11)
      ansible.windows.win_powershell:
        script: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Ensure Chocolatey in PATH
      ansible.windows.win_environment:
        state: present
        name: PATH
        value: C:\ProgramData\chocolatey\bin
        level: machine

    - name: Refresh PATH to include Chocolatey
      ansible.windows.win_powershell: 
        script: |
          $env:Path += ";C:\ProgramData\chocolatey\bin"

    - name: Install .NET SDK using Chocolatey
      ansible.windows.win_powershell: 
        script: |
          choco install dotnet-sdk -y --no-progress
      # args:
      #   chdir: C:\

    - name: Install Visual Studio Build Tools
      ansible.windows.win_powershell: 
        script: |
          choco install visualstudio2022buildtools -y --no-progress
      # args:
      #   chdir: C:\

    # - name: Verify .NET installation
    #   win_powershell: dotnet --version
    #   register: dotnet_version

    # - debug:
    #     msg: "Installed .NET version is {{ dotnet_version.stdout }}"
